# syntax=docker/dockerfile:1.4
FROM node:12.18.2 AS installer
COPY --link projects/service/ projects/service/
WORKDIR projects/service
RUN yarn install

FROM installer as builder
ENTRYPOINT [ "yarn", "start" ]

FROM installer as tester
RUN mkdir -p projects/service/target/test-reports/
RUN yarn test-ci