# syntax=docker/dockerfile:1.4
FROM node:12.18.2 AS installer
COPY --link projects/cloudfront/ /projects/cloudfront/
WORKDIR /projects/cloudfront

COPY projects/cloudfront/src/sum.js /cloudfront-service/static/js/
RUN yarn install

FROM installer as builder
ENTRYPOINT [ "yarn", "start" ]
