name: job
description: "A job"
maintainer: ["MPyL"]
mpylVersion: 1.0.10
stages:
  build: "Docker Build"
  test: "Echo Test"
  deploy: "Kubernetes Job Deploy"
deployment:
  namespace: job
  rancher:
    projectId:
      all: "p-11111"
  kubernetes:
    job:
      cron:
        all:
          schedule: "0 22 * * *"
          timeZone: "Europe/Amsterdam"

dependencies:
  test:
    - projects/service/file.py
