---
# Source: job/templates/service-account
apiVersion: v1
imagePullSecrets:
- name: bigdataregistry
kind: ServiceAccount
metadata:
  labels:
    name: job
    app.kubernetes.io/version: pr-1234
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: job
    maintainers: MPyL
    maintainer: MPyL
    version: pr-1234
  name: job
---
# Source: job/templates/cronjob
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    name: job
    app.kubernetes.io/version: pr-1234
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: job
    app.kubernetes.io/instance: job
    maintainers: MPyL
    maintainer: MPyL
    version: pr-1234
  name: job
spec:
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            image: ghcr.io/samtheisens/job:pr-1234
          labels:
            name: job
            app.kubernetes.io/version: pr-1234
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: job
            app.kubernetes.io/instance: job
            maintainers: MPyL
            maintainer: MPyL
            version: pr-1234
          name: job
        spec:
          containers:
          - env: []
            image: ghcr.io/samtheisens/job:pr-1234
            imagePullPolicy: Always
            name: job
            resources:
              limits:
                cpu: 500m
                memory: 1024Mi
              requests:
                cpu: 100m
                memory: 512Mi
          restartPolicy: Never
          serviceAccount: job
          serviceAccountName: job
      ttlSecondsAfterFinished: 3600
  schedule: 0 22 * * *
