apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mpyl-gha-demo
spec:
  destination:
    name: ''
    namespace: pr-2
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/charts
    repoURL: 'https://github.com/SamTheisens/mpyl-gha-example.git'
    targetRevision: feature/TECH-XXX-github-actions-publish-images
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
