name: build
on:
  push:
    branches-ignore: [ 'main' ]

permissions: write-all

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    env:
      MPYL_VERSION: "1.6.7"
      DOCKER_REGISTRY_USR: ${{ github.actor }}
      DOCKER_REGISTRY_PSW: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Manual checkout
        run: git clone --shallow-exclude main --single-branch --branch ${{ github.ref_name }} https://github.com/SamTheisens/mpyl-gha-example.git $(pwd)

      - name: Tag grafted root revision
        run: git tag origin/main $(git log --pretty=format:"%H" | tail -n 1)

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: |
            Pipfile.lock

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: pipenv install -d

      - name: MPyL health
        run: pipenv run mpyl health --ci

      - name: Build status
        run: pipenv run mpyl build status

      - name: Find PR number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        if: github.ref_name != 'main'
        with:
          state: open

      - name: Pull cache
        env:
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: pipenv run mpyl build artifacts pull --pr ${{ steps.findPr.outputs.pr }} --path cache

      - name: Build status after pull
        run: pipenv run mpyl build -v status

      - name: Build run
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: pipenv run run

      - name: Push manifests
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: pipenv run mpyl build artifacts push --pr ${{ steps.findPr.outputs.pr }} --path manifests --artifact-type argo

      - name: Push cache
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: pipenv run mpyl build artifacts push --pr ${{ steps.findPr.outputs.pr }} --path cache --artifact-type cache
