name: build
on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install

      - name: Check Health
        run: pipenv run health

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker

      - name: Run build
        run: pipenv run run
        env:
          PR_NUMBER: 1234
          MPYL_CONFIG_PATH: mpyl_config.yml

      - name: Build and push
        if: always()
        uses: docker/build-push-action@v4
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max