name: build
on:
  push:
    branches-ignore: [ 'main' ]

permissions: write-all

jobs:
  build-pipeline:
    runs-on: ubuntu-latest
    env:
      MPYL_VERSION: "1.6.7"
      DOCKER_REGISTRY_USR: ${{ github.actor }}
      DOCKER_REGISTRY_PSW: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Manual checkout
        run: git clone --shallow-exclude main --single-branch --branch ${{ github.ref_name }} https://github.com/SamTheisens/mpyl-gha-example.git $(pwd)

      - name: Tag grafted root revision
        run: git tag origin/main $(git log --pretty=format:"%H" | tail -n 1)

      - name: Install MPyL
        continue-on-error: true
        run: pip install mpyl==${{ env.MPYL_VERSION }}

      - name: MPyL health
        run: mpyl health --ci

      - name: Build status
        run: mpyl build status

      - name: Find PR number
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        if: github.ref_name != 'main'
        with:
          state: open

      - name: Pull cache
        env:
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: mpyl build artifacts pull --pr ${{ steps.findPr.outputs.pr }} --path cache

      - name: Build status after pull
        run: mpyl build -v status

      - name: Build run
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: mpyl build run --ci

      - name: Push manifests
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: mpyl build artifacts push --pr ${{ steps.findPr.outputs.pr }} --path manifests --artifact-type argo

      - name: Push cache
        env:
          PR_NUMBER: ${{ steps.findPr.outputs.pr }}
          ARGOCD_GITHUB_TOKEN: ${{ secrets.ARGOCD_GITHUB_TOKEN }}
        run: mpyl build artifacts push --pr ${{ steps.findPr.outputs.pr }} --path cache --artifact-type cache
